"""add risk snapshots

Revision ID: 90e75f8c7e63
Revises: 5f937a679090
Create Date: 2026-09-12 07:02:08.097508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e75f8c7e63'
down_revision: Union[str, Sequence[str], None] = '5f937a679090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cri', sa.Float(), nullable=False),
    sa.Column('pri', sa.Float(), nullable=False),
    sa.Column('eri', sa.Float(), nullable=False),
    sa.Column('sri', sa.Float(), nullable=False),
    sa.Column('overall_risk', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_snapshots_id'), 'risk_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_risk_snapshots_timestamp'), 'risk_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_snapshots_timestamp'), table_name='risk_snapshots')
    op.drop_index(op.f('ix_risk_snapshots_id'), table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    # ### end Alembic commands ###
